# ----------------------------------------------------
# J-VIBE Guide: Jekyll Configuration
# ----------------------------------------------------

# Site Settings
title: J-VIBE Guide
email: your-email@example.com
description: >-
  Your essential guide to Japan's music scene, tickets, and fan activities for Asia visitors.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build Settings
# Markdownのパーサーにkramdownを使用
markdown: kramdown
# ハイライト表示のエンジン
highlighter: rouge
# ページ生成から除外するファイル/フォルダ
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/

# Permalinks
# ページURLの構造を定義します (例: /major-star/)
permalink: /:basename/

# Collection Settings (多言語コンテンツ管理のために使用)
# 将来的に多言語ファイルやアーティストデータを_dataフォルダに格納する設定
collections:
  artists:
    output: true
    permalink: /artists/:name/
